name: Release Docker

on:
  push:
    tags:
      - v**
      - '!**beta**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mmx233/bitsrunlogin-go

      - name: Setup QEMU Emulator
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Setup Docker Buildx Command
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.rgs_u }}
          password: ${{ secrets.rgs_p }}

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Setup Release Cli
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "Mmx233/GoReleaseCli"
          latest: true
          fileName: 'release_linux_amd64.tar.gz'
          extract: true
          out-file-path: './build/'

      - name: Build Binary
        run: |
          ./build/release ./cmd/bitsrun --platforms linux/amd64,linux/arm64,linux/386,linux/ppc64le,linux/riscv64,linux/s390x --divider "/" --output-format post --output build/output
          ./build/release ./cmd/bitsrun --platforms linux/arm --extra-arches  --divider "/" --output-format post --output build/output --disable-auto-clean

      - name: Build Docker Image and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile.ci
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v6,linux/arm/v7,linux/ppc64le,linux/riscv64,linux/s390x
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}